name: provision resources

on:
  workflow_call:

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: init
        run: terraform init

      - name: validate
        run: terraform validate -no-color

      - name: plan
        id: plan
        run: terraform plan -out="tfplan"

      - name: apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve "tfplan"
