name: provision resources

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      WORKING_DIRECTORY:
        required: false
        type: string
        default: "."
      APPLY_ON_PR:
        required: false
        type: string
        default: 'false'
      DESTROY_ON_MERGE:
        required: false
        type: string
        default: 'false'
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ inputs.AWS_REGION }}

jobs:
  deploy-terraform:
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: init
        run: terraform init

      - name: validate
        run: terraform validate -no-color

      - name: plan
        id: plan
        run: terraform plan -out="tfplan"

      - name: apply
        if: ${{ inputs.APPLY_ON_PR == 'true' }} || github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve "tfplan"
      
      - name: destroy
        if: ${{ inputs.DESTROY_ON_MERGE == 'true' }} && github.ref == 'refs/heads/main'
        run: terraform destroy -input=false -auto-approve
